{% set name = "napari-tiff" %}
{% set version = "0.1.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_tiff-{{ version }}.tar.gz
  sha256: d78f34991b61a44b0f3a547018a5db5b724ac05b2e6fd74f38de32c186158564

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - imagecodecs >=2023.8.12
    - fsspec
    - kerchunk
    - numpy
    - tifffile >=2024.7.21
    - zarr

test:
  imports:
    - napari_tiff
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/napari/napari-tiff
  summary: official napari tiff reader and writer.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jni
    - DragaDoncila
    - psobolewskiPhD
